### ISSUE TITLE
aten::scaled_dot_product_attention export fail

### ISSUE THREAD

**Issue by hunterzju** [sophgo/ChatGLM2-TPU#6]
执行export_onnx失败：
Exporting the operator 'aten::scaled_dot_product_attention' to ONNX opset version 15 is not supported.

请问pytorch和onnx版本分别是什么？

**Comment by HarmonyHu** [comment]
使用tpu-mlir用的docker就可以了 @hunterzju

**Comment by OptimistQAQ** [comment]
请问执行onnx导出成功了吗？

**Comment by hunterzju** [comment]
> 请问执行onnx导出成功了吗？

改了一下chatglm模型的代码导出成功了，里面chatglm2-6b模型的实现代码里搜这个op，它判断torch版本>2.0就用这个操作;手动把那一段注释掉就好
